{% set version = "1.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsample
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsample_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsample/rsample_{{ version }}.tar.gz
  sha256: 90d2ae86d27a397ba9d8d010e7dea5c7b86fecbec7e9af273db0c2e8c374b8ba

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-furrr
    - r-generics
    - r-glue
    - r-pillar
    - r-purrr
    - r-rlang >=0.4.10
    - r-slider >=0.1.5
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-vctrs >=0.5.0
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-furrr
    - r-generics
    - r-glue
    - r-pillar
    - r-purrr
    - r-rlang >=0.4.10
    - r-slider >=0.1.5
    - r-tibble
    - r-tidyr
    - r-tidyselect
    - r-vctrs >=0.5.0

test:
  commands:
    - $R -e "library('rsample')"           # [not win]
    - "\"%R%\" -e \"library('rsample')\""  # [win]

about:
  home: https://tidymodels.github.io/rsample
  license: MIT
  summary: 'Classes and functions to create and summarize different types of resampling objects (e.g. bootstrap, cross-validation). '
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: rsample
# Title: General Resampling Infrastructure
# Version: 0.0.5
# Authors@R: c( person(given = "Max",    family = "Kuhn",    email = "max@rstudio.com",      role = c("aut", "cre")), person(given = "Fanny",  family = "Chow",    email = "fannybchow@gmail.com", role = c("aut")), person(given = "Hadley", family = "Wickham", email = "hadley@rstudio.com",   role = c("aut")), person("RStudio", role = "cph"))
# Maintainer: Max Kuhn <max@rstudio.com>
# Description: Classes and functions to create and summarize different types of resampling objects (e.g. bootstrap, cross-validation).
# Imports: dplyr, purrr, tibble, rlang (>= 0.4.0), methods, generics, utils, tidyselect, furrr
# Depends: R (>= 3.1), tidyr
# Suggests: ggplot2, testthat, rmarkdown, knitr, AmesHousing, recipes (>= 0.1.4), broom
# URL: https://tidymodels.github.io/rsample
# BugReports: https://github.com/tidymodels/rsample/issues
# License: GPL-2
# Encoding: UTF-8
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-12 21:46:43 UTC; max
# Author: Max Kuhn [aut, cre], Fanny Chow [aut], Hadley Wickham [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2019-07-12 22:20:11 UTC
