{% set version = '0.0.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsample
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsample_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsample/rsample_{{ version }}.tar.gz
  sha256: a8671e62293eb134eb39072955b2732462388b2c2fc481aba924be23cb492038

build:
  merge_build_host: True  # [win]
  number: 1000
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-dplyr
    - r-generics
    - r-purrr
    - r-rlang
    - r-tibble >=2.0.0
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-generics
    - r-purrr
    - r-rlang
    - r-tibble >=2.0.0
    - r-tidyr

test:
  commands:
    - $R -e "library('rsample')"           # [not win]
    - "\"%R%\" -e \"library('rsample')\""  # [win]

about:
  home: https://tidymodels.github.io/rsample
  license: GPL-2
  summary: 'Classes and functions to create and summarize different types of resampling objects
    (e.g. bootstrap, cross-validation). '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: rsample
# Title: General Resampling Infrastructure
# Version: 0.0.4
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut")), person("RStudio", role = "cph"))
# Maintainer: Max Kuhn <max@rstudio.com>
# Description: Classes and functions to create and summarize different types of resampling objects (e.g. bootstrap, cross-validation).
# Imports: dplyr, purrr, tibble (>= 2.0.0), rlang, methods, generics
# Depends: R (>= 3.1), tidyr
# Suggests: ggplot2, testthat, rmarkdown, knitr, AmesHousing, recipes (>= 0.1.4), broom
# URL: https://tidymodels.github.io/rsample
# BugReports: https://github.com/tidymodels/rsample/issues
# License: GPL-2
# Encoding: UTF-8
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-01-07 01:49:42 UTC; max
# Author: Max Kuhn [aut, cre], Hadley Wickham [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2019-01-07 17:00:07 UTC
