{% set version = '0.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsample
  version: {{ version|replace("-", "_") }}

source:
  fn: rsample_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsample_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsample/rsample_{{ version }}.tar.gz
  sha256: c19308b3a859d9029fb754762534218096cd9b890f6c59a8b71aa89563eab4bd

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-dplyr
    - r-purrr
    - r-tibble
    - r-rlang
    - r-generics
    - r-tidyr
  run:
    - r-base
    - r-dplyr
    - r-purrr
    - r-tibble
    - r-rlang
    - r-generics
    - r-tidyr

test:
  commands:
    - $R -e "library('rsample')"           # [not win]
    - "\"%R%\" -e \"library('rsample')\""  # [win]

about:
  home: https://topepo.github.io/rsample
  license: GPL-2
  summary: 'Classes and functions to create and summarize different types of resampling objects
    (e.g. bootstrap, cross-validation). '
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
