travis:
  secure:
    BINSTAR_TOKEN: XD9R22G7GDvYCrIrQEH63FBxIbRqjq+6RlDWboORxu2BGLhCWhbl4tCZX31WG2Nb1/Fijo0Awc9WXuRmhOmftvPIaSgfx9ZJs7XXKUcOJjCtq8XeRoz29V1GBYw5kE40DLWPx8lsGgAzjMGOE8s3jj6IYFifbZMkMAHwqubuiAYG62XV+LRm+W0iPBRgV6/ChzqBr8nxfS5AC0CNkzM+O2ej5YxBF7xQWy0x7ZrQOcei+HEM1w7Tr6JyuN0MDrz8gLHK3HvUHg9HdR68jCTPe2rxV1FSlaB0+AIJHBNVJBRPxUl1wHLvHO1zljFNEOffuxC+ySzjE88434Zp4ukHE/XlY7EV8f3GuB3kmPSZaok1ZTxFAKaiJv6ONGna34Z/B3VF+ABuHVqrBdQGf1h+gt7qX9yDYeTVdwEIIcBsDc3QLV+FrxgsazP6p7r/7kA8UKx1GhSGdvL+O2qJEhNAAljSAQXdQzlR2ktz6SCYEECd25b6olLz4o9f9XWbte3hnTUXg+ukwnPKmooFowEjFDHouhn9F+cfW4iPO+mCtSZXvP8iRNyWTs0E5NjgCbWWVZaOsiEjNQbjiTl1ca2dnZai26oDnl2BTm85QQgETbyA8woHwc6TPfcbs24bHnK+ygYc6D47eVzKeCBvtGTOc8TWRdmp2rAz//lU3XEVGAI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
