travis:
  secure:
    BINSTAR_TOKEN: DPg5D2IZ4bfbOieTbphCnjWCHY9LTl2lv+Pfr+IZKP0NlSW4wu8EqvNAq36EApYgQryqs0qxRNz4HyNe5o2+BM1WRpo7QNmJ/PjeXlUN7nnAD6svlKp9WaE5+CuhTf9hk3sH1KGffjq1my/4x49GPqJCLQMJ083EsRVbN0UNWej2Q+y/WDv+hyjlXbr1QxgQjtmWArGpaYNnv4sfiVewjJD5PvIEoy42dNgkAL6AE6fuMPYaE5DLyFWIEDZTtr1CN+w1mUGcRqjdt6jM5t0J7+caTGPYUn1hzhIuwLC8JC2Wjd40w0/E9RntfLUcfp5riSq0N6qjku6/QVKY/oVLpKSdwhU7gvinsxXC6hGej+RQePsaNiX3rBbGUUVogzmXFHrF3chh/OiQzQAiydTK8eMyO4ulu/+O8BiLHOJUWE31BNSOUsUhEPKVczYn7HKiSgaZQWnlWpA+5VQyycE8c7BuZPaDEdTFXI9oaEcMet9tjju+ySQZY6XYu9aK68sec6oeeJC0J80jncU5O0D9F256KhwTHh26rippXuy0yRizGPeTtydFMDTwbFKTY7L/PNT++qce6JHi2s5PYOg7A47zEPMB492vkk3s0/+c/GJRHq26xgAhIqTVoYpUL8XkrdbMyBbY2+ugjAmAoA0wy3inyTpkB8APOozq4aSQugg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
